#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Estilizando, testando e compilando o projeto antes de realizar o commit'

# Valida os padrões do Prettier
yarn check-format ||
(
  echo '🤢🤮🤢🤮 MEU DEUS! O seu código está feio!! 🤢🤮🤢🤮
    A validação do Prettier falhou. Execute yarn format, adicione as alterações no git e tente o commit novamente.';
  false;
)

# Valida os padrões do ESLint
yarn check-lint ||
(
  echo '😤🏀👋😤 Quer quebrar as regras né, malandro?! 😤🏀👋😤
      A validação do ESLint falhou. Faça as alterações listadas acima, adicione as alterações no git e tente o commit novamente.'
  false; 
)

# Valida os padrões Typescript
yarn check-types ||
(
  echo '🤡😂❌🤡 Você não passou na chacagem da tipagem 🤡😂❌🤡
    Você realmente está tentando meter essa? Faça as alterações listadas acima.'
  false;
)

# Se tudo passar... Podemos testar a build
echo '🤔🤔🤔🤔... Hmmm, ok... O código me parece bom... Tentando compilar agora. 🤔🤔🤔🤔'

yarn build ||
(
    echo '❌👷🔨❌ Espero que não esteja no fim do expediente... A build não rolou ❌👷🔨❌
      A compilação do Next falhou: Verifique os erros acima e descubra o motivo.'
    false;
)

# Se tudo passar... Agora podemos fazer o commit
echo '✅✅✅✅ Você ganhou dessa vez... Vou commitar isso para você. ✅✅✅✅'
